### ISSUE TITLE
source to doomedit missing?

### ISSUE THREAD

**Issue by neozeed** [Kweepa/vicdoom#3]
https://github.com/Kweepa/vicdoom/tree/16ada99c506888ae410f91d7fb97b2e1f6b5e9fc

in this commit it mentions adding the source to doomedit, and there is some 'cooked' batch files that mention it, but it's not in the tree.

**Comment by Kweepa** [comment]
Ah, yes, I never uploaded the source.
It's written in Adventure Game Studio :)
I suppose the best solution is to just add a zip of the source, since none of it is diffable. It should open and run with recent versions of Adventure Game Studio.

**Comment by neozeed** [comment]
AWESOME!
